title: "Modo Tab Mount"
logo: /images/modo_tab_mout_animation2x.gif
description: <p>Sleek magnetic tablet mount with a smart ESP32-C3/ESPHome power supply, designed for seamless Home Assistant integration. Fits standard EU wall boxes.</p>
